version: '3.8'

services:

    # PHP-FPM - Service
    app:
        build:
            context: .
            dockerfile: Dockerfile

        container_name: laravue-app
        restart: unless-stopped
        tty: true
        working_dir: /var/www

        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini

        networks:
            - app-network

    # Nginx - Service
    webserver:
        image: nginx:alpine
        container_name: laravue-webserver
        restart: unless-stopped
        tty: true

        ports:
            - "80:80"
            - "443:443"

        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf

        networks:
            - app-network

    # MariaDB - Service
    db:
        image: mariadb:10.7.1
        container_name: laravue-db
        restart: unless-stopped
        tty: true

        ports:
            - "3306:3306"

        environment:
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'

        volumes:
            - mariadbdata:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf

        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: laravue-pma
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - 8081:80
        networks:
            - app-network

# Volumes
volumes:
    mariadbdata:
        driver: local

# Networks
networks:
    app-network:
        driver: bridge

